import requests
wen_data =[
{'graph': 'AWSLambda', "s": 'faas:Environment', "p": "dul:hasDataValue", "o":"Firecracker" },
{'graph': 'AWSLambda', "s": 'faas:AWSLambda', "p": "faas:hasFeature", "o":"faas:Environment" },
{'graph': 'AWSLambda', "s": 'faas:AWSLambda', "p": "faas:hasFeature", "o":"faas:FileDescriptors" },
{'graph': 'AWSLambda', "s": 'faas:FileDescriptors', "p": "dul:hasDataValue", "o":1024 },
{'graph': 'AWSLambda', "s": 'faas:AWSLambda', "p": "faas:hasFeature", "o":"faas:ProcessThreadLimit" },
{'graph': 'AWSLambda', "s": 'faas:ProcessThreadLimit', "p": "dul:hasDataValue", "o": 1024},
{'graph': 'AWSLambda', "s": 'faas:AWSLambda', "p": "faas:hasFeature", "o":"faas:InstanceLimit" },
{'graph': 'AWSLambda', "s": 'faas:InstanceLimit', "p": "dul:hasDataValue", "o": "500-3000 (varies per region)" },
{'graph': 'AWSLambda', "s": 'faas:AWSLambda', "p": "faas:hasFeature", "o":"faas:Payload" },
{'graph': 'AWSLambda', "s": 'faas:Payload', "p": "dul:hasDataValue", "o": "6 MB" },
{'graph': 'AWSLambda', "s": 'faas:AWSLambda', "p": "faas:hasFeature", "o":"faas:PackageSizeLimit" },
{'graph': 'AWSLambda', "s": 'faas:PackageSizeLimit', 'p': "dul:hasDataValue", "o": "250 MB"},
{'graph': 'AWSLambda', "s": 'faas:CPU', "p": "dul:hasDataValue", "o":"Proportional to memory" },
{'graph': 'AWSLambda', "s": 'faas:AWSLambda', "p": "faas:hasFeature", "o":"faas:CPU" },
{'graph': 'AWSLambda', "s": 'faas:AWSLambda', "p": "faas:hasFeature", "o":"faas:DeploymentMethods" },
{'graph': 'AWSLambda', "s": 'faas:DeploymentMethods', "p": "dul:hasDataValue", "o":"Source Code" },
{'graph': 'AWSLambda', "s": 'faas:DeploymentMethods', "p": "dul:hasDataValue", "o":"Docker container" },
{'graph': 'AWSLambda', "s": 'faas:AWSLambda', "p": "faas:hasFeature", "o":"faas:Memory" },
{'graph': 'AWSLambda', "s": 'faas:Memory', "p": "dul:hasDataValue", "o": "128-3000 MB"},
{'graph': 'AWSLambda', "s": 'faas:AWSLambda', "p": "faas:hasFeature", "o":"faas:Timeout" },
{'graph': 'AWSLambda', "s": 'faas:Timeout', "p": "dul:hasDataValue", "o": 900 },
{'graph': 'AWSLambda', "s": 'faas:AWSLambda', "p": "faas:hasFeature", "o":"faas:LocalDisk" },
{'graph': 'AWSLambda', "s": 'faas:LocalDisk', "p": "dul:hasDataValue", "o": "512 MB" },
{'graph': 'AWSLambda', "s": 'faas:AWSLambda', "p": "faas:hasFeature", "o":"faas:SupportedRegion" },
{'graph': 'AWSLambda', "s": 'faas:SupportedRegion', 'p': "dul:hasDataValue", "o": 20},
{'graph': 'AWSLambda', "s": 'faas:AWSLambda', "p": "faas:hasFeature", "o":"faas:RuntimeOS" },
{'graph': 'AWSLambda', "s": 'faas:RuntimeOS', 'p': "dul:hasDataValue", "o": "Amazon Linux (2)"},
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:Environment', "p": "dul:hasDataValue", "o":"Docker" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:MicrosoftAzureFunctions', "p": "faas:hasFeature", "o":"faas:Environment" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:MicrosoftAzureFunctions', "p": "faas:hasFeature", "o":"faas:FileDescriptors" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:FileDescriptors', "p": "dul:hasDataValue", "o":"Unknown" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:MicrosoftAzureFunctions', "p": "faas:hasFeature", "o":"faas:ProcessThreadLimit" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:ProcessThreadLimit', "p": "dul:hasDataValue", "o": "Unknown"},
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:MicrosoftAzureFunctions', "p": "faas:hasFeature", "o":"faas:InstanceLimit" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:InstanceLimit', "p": "dul:hasDataValue", "o": 200},
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:MicrosoftAzureFunctions', "p": "faas:hasFeature", "o":"faas:Payload" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:Payload', "p": "dul:hasDataValue", "o": "100 MB" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:MicrosoftAzureFunctions', "p": "faas:hasFeature", "o":"faas:PackageSizeLimit" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:PackageSizeLimit', 'p': "dul:hasDataValue", "o": "250 MB"},
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:CPU', "p": "dul:hasDataValue", "o":"Unknown" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:MicrosoftAzureFunctions', "p": "faas:hasFeature", "o":"faas:CPU" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:MicrosoftAzureFunctions', "p": "faas:hasFeature", "o":"faas:DeploymentMethods" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:DeploymentMethods', "p": "dul:hasDataValue", "o":"Source Code" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:DeploymentMethods', "p": "dul:hasDataValue", "o":"External services" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:MicrosoftAzureFunctions', "p": "faas:hasFeature", "o":"faas:Memory" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:Memory', "p": "dul:hasDataValue", "o": "1536 MB"},
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:MicrosoftAzureFunctions', "p": "faas:hasFeature", "o":"faas:Timeout" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:Timeout', "p": "dul:hasDataValue", "o": 600 },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:MicrosoftAzureFunctions', "p": "faas:hasFeature", "o":"faas:LocalDisk" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:LocalDisk', "p": "dul:hasDataValue", "o": "500 MB" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:MicrosoftAzureFunctions', "p": "faas:hasFeature", "o":"faas:SupportedRegion" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:SupportedRegion', 'p': "dul:hasDataValue", "o": 19},
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:MicrosoftAzureFunctions', "p": "faas:hasFeature", "o":"faas:RuntimeOS" },
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:RuntimeOS', 'p': "dul:hasDataValue", "o": "Windows Server 1809"},
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:RuntimeOS', 'p': "dul:hasDataValue", "o": "Debian 9"},
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:RuntimeOS', 'p': "dul:hasDataValue", "o": "Debian 10"},
{'graph': 'MicrosoftAzureFunctions', "s": 'faas:RuntimeOS', 'p': "dul:hasDataValue", "o": "Ubuntu 18.04"},
{'graph': 'GoogleCloudFunctions', "s": 'faas:Environment', "p": "dul:hasDataValue", "o":"gVisor" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:GoogleCloudFunctions', "p": "faas:hasFeature", "o":"faas:FileDescriptors" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:GoogleCloudFunctions', "p": "faas:hasFeature", "o":"faas:Environment" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:FileDescriptors', "p": "dul:hasDataValue", "o":"Unknown" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:GoogleCloudFunctions', "p": "faas:hasFeature", "o":"faas:ProcessThreadLimit" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:ProcessThreadLimit', "p": "dul:hasDataValue", "o": "Unknown"},
{'graph': 'GoogleCloudFunctions', "s": 'faas:GoogleCloudFunctions', "p": "faas:hasFeature", "o":"faas:InstanceLimit" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:InstanceLimit', "p": "dul:hasDataValue", "o": 3000},
{'graph': 'GoogleCloudFunctions', "s": 'faas:MicrosoftAzureFunctions', "p": "faas:hasFeature", "o":"faas:Payload" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:Payload', "p": "dul:hasDataValue", "o": "10 MB" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:GoogleCloudFunctions', "p": "faas:hasFeature", "o":"faas:PackageSizeLimit" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:PackageSizeLimit', 'p': "dul:hasDataValue", "o": "500 MB"},
{'graph': 'GoogleCloudFunctions', "s": 'faas:CPU', "p": "dul:hasDataValue", "o":"Proportional to memory" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:GoogleCloudFunctions', "p": "faas:hasFeature", "o":"faas:CPU" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:GoogleCloudFunctions', "p": "faas:hasFeature", "o":"faas:DeploymentMethods" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:DeploymentMethods', "p": "dul:hasDataValue", "o":"Source Code" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:DeploymentMethods', "p": "dul:hasDataValue", "o":"External services" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:DeploymentMethods', "p": "dul:hasDataValue", "o":"Docker Container" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:GoogleCloudFunctions', "p": "faas:hasFeature", "o":"faas:Memory" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:Memory', "p": "dul:hasDataValue", "o": "128-2048 MB"},
{'graph': 'GoogleCloudFunctions', "s": 'faas:GoogleCloudFunctions', "p": "faas:hasFeature", "o":"faas:Timeout" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:Timeout', "p": "dul:hasDataValue", "o": 540 },
{'graph': 'GoogleCloudFunctions', "s": 'faas:GoogleCloudFunctions', "p": "faas:hasFeature", "o":"faas:LocalDisk" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:LocalDisk', "p": "dul:hasDataValue", "o": ">512 MB" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:GoogleCloudFunctions', "p": "faas:hasFeature", "o":"faas:SupportedRegion" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:SupportedRegion', 'p': "dul:hasDataValue", "o": 32},
{'graph': 'GoogleCloudFunctions', "s": 'faas:GoogleCloudFunctions', "p": "faas:hasFeature", "o":"faas:RuntimeOS" },
{'graph': 'GoogleCloudFunctions', "s": 'faas:RuntimeOS', 'p': "dul:hasDataValue", "o": "Ubuntu 18.04"},
]
manual_fixes = [
    # {'s':"faas:IDEsandTextEditors", "p": "rdfs:subClassOf" , "o": "faas:Development"},
    # {'s':"faas:InstallationTargetHosts", "p": "rdfs:subClassOf" , "o": "faas:Installation"},
    # {'s':"faas:OrchestratingFunctionLanguages", "p": "rdfs:subClassOf" , "o": "faas:FunctionOrchestrator"}
{'graph': 'faas:Fission', 's': 'faas:GitHubIssues', 'p': 'dul:hasSource', 'o': 'Github API'}

]

APIGATEWAY_ENDPOINT = "https://06efiaq9xl.execute-api.eu-west-1.amazonaws.com/test/platforms"
for triple in manual_fixes:
    response = requests.put(url=APIGATEWAY_ENDPOINT, params=triple)
    if response.status_code != 200:
        print(response.json()) 